### ISSUE TITLE
users.json

### ISSUE THREAD

**Issue by Hydralisca** [giacomoferretti/mcdapi-telegram-bot#1]
Ciao, grazie per aver condiviso il tuo lavoro.

Sto provando ad eseguire il tuo programma, ma giustamente cerca il file users.json (così anche per le offerte).

Come posso crearli se non riesco a generare degli account validi?

**Comment by giacomoferretti** [comment]
Ciao, mi potresti mandare i log degli errori? Non riesco a capire precisamente dove sia il problema, dato che `users.json` dovrebbe crearlo automaticamente. 

Per le offerte invece devi guardare qui https://github.com/giacomoferretti/mcdapi-tools su come ricavare `offers.json`.

**Comment by giacomoferretti** [comment]
Ti è per caso uscito questo messaggio?

```
2019-06-02 19:27:22,826 - utils.users - WARNING - "users.json" not found or empty.
```

Se sì, non ci sono problemi. In teoria appena un utente interagirà con il bot dovrebbe creare il file ed aggiungere le informazioni dell'utente dentro allo stesso, ma nella versione attuale non funziona. La prossima versione dovrebbe fixare il problema.

**Comment by Hydralisca** [comment]
Grazie per la risposta.

Per quanto riguarda la generazione delle offerte, nell'esecuzione di offers_scrapper.py, compare il seguente errore:

Starting scraping 1250 offers using mcdapi (0.1.4)...
Traceback (most recent call last):
  File "offers_scraper.py", line 92, in <module>
    main()
  File "offers_scraper.py", line 56, in main
    data=endpoints.DEVICE_REGISTRATION['body'].format(username, password), headers=headers)
KeyError: 'username'

**Comment by giacomoferretti** [comment]
`offers_scraper.py` per ora funziona solo con `mcdapi==0.1.3` dato che nella versione 0.1.4 ho cambiato i vari metodi. Se riesco entro stasera sistemo anche questo, per ora usa `mcdapi` versione 0.1.3.

**Comment by Hydralisca** [comment]
Ti ringrazio, sei molto gentile.
Se nel mentre trovo qualcosa di rilevante da segnalare, lo posto qui.
