### ISSUE TITLE
Invio del "menu" in chat privata

### ISSUE THREAD

**Issue by itsrxns** [giacomoferretti/mcdapi-telegram-bot#3]
Ciao, ti ringrazio per aver reso pubblico il tuo lavoro, è stato davvero interessante e utile!
Ho provato a realizzare uno stesso bot seguendo le tue indicazioni e non ho avuto nessun problema! 
L'unica cosa che mi piacerebbe aggiungere è la possibilità di far generare il "menu" del bot in chat privata a seconda di chi ha lanciato il comando /start nel gruppo, è possibile? :D

**Comment by giacomoferretti** [comment]
Grazie per averlo provato!

I bot su Telegram non possono mandare messaggi agli utenti a meno che loro non abbiamo fatto partire il bot in chat privata, quindi non credo sia possibile. 🙁
